### ISSUE TITLE
Wraparound behavior on terminals taller than 63 lines

### ISSUE THREAD

**Issue by bbarenblat** [taviso/lotusdrv#7]
Running 1-2-3 release 3.4 with this driver on a terminal with 64 or more lines causes the bottom of the display to mirror the top of the display:

![wraparound](https://user-images.githubusercontent.com/629239/126799980-b8673858-48a4-4c46-b8d0-3ae9196056d3.png)

I’m not sure if this is a driver bug, a fundamental limitation of 1-2-3’s graphics API, or a dosemu2 bug, but it seems worth documenting in any case. (Beyond this issue, the driver seems to work great with release 3.4. Thanks for making it a reality!)

I’m using dosemu2-2.0pre8-20210718-3057-gd488fe7b9 (revision 6756).

`stty rows $((LINES > 63 ? 63 : LINES))` (or `tmux setw force-height 63`, if you’re in tmux) is a good workaround.

**Comment by taviso** [comment]
Hmm, interesting, confirmed! It seems to happen with wordperfect and foxpro too, so I think it must be a dosemu2 bug. I'll file a bug.

![Screenshot 2021-07-23 081212](https://user-images.githubusercontent.com/123814/126802926-d6dc679a-8ec9-4b83-b356-e869113a1d08.png)
![Screenshot 2021-07-23 081041](https://user-images.githubusercontent.com/123814/126802929-5eb6685e-6cf0-465b-9275-291ad4691eac.png)

**Comment by taviso** [comment]
Let's see what Stas says - I'm happy to hear it works in 3.4, I hadn't tested it!

**Comment by taviso** [comment]
Stas is quick - https://github.com/dosemu2/dosemu2/commit/889ce261ce9bf2962d67e4c3de844b4c35073e7d

**Comment by taviso** [comment]
Seems to work here for me with that patch!
